######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 4 16:36:31 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT+=network

# Input
HEADERS += client.h server.h ui.h
SOURCES += client.cpp main.cpp server.cpp ui.cpp
